#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: iocage
# REQUIRE: LOGIN cleanvar sshd
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable zjail:
#
# iocage_enable="YES"
#
#

. /etc/rc.subr

name="iocage"
rcvar=iocage_enable

# read configuration and set defaults
load_rc_config "$name"
: ${iocage_enable="NO"}

start_cmd="iocage_start"
stop_cmd="iocage_stop"

iocage_start()
{
    if checkyesno ${rcvar}; then
        /usr/local/sbin/iocage rcboot
    fi
}

iocage_stop()
{
    if checkyesno ${rcvar}; then
        /usr/local/sbin/iocage rcshutdown
    fi
}

run_rc_command "$1"
