#!/bin/sh
#-------------------------------------------------------------------------+
# Copyright (c) 2014-2015, iocage
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

unset LC_ALL
unset LANG

PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

if [ "${1}" = "--version" -o "${1}" = "version" ] ; then
    echo "iocage DEVELOP (2015-11-19)"
    exit 0
fi

# Check if the system has ZFS available. That is required for iocage to work properly.
# Exit if it doesn't.
if [ "$(zpool list)" = 'no pools available' ] ; then
    echo "  ERROR: ZFS is required for iocage to work and I can't find any pools available." >&2
    exit 1
fi

if [ "$(uname -K)" -lt "903000" ]; then
    echo "  ERROR: Unsupported RELEASE found. Please upgrade to 9.3-RELEASE or later." >&2
    exit 1
fi

# Check if libs are available
if [ -e "./lib/ioc-common" ] ; then
    LIB="./lib"
elif [ -e "/usr/local/lib/iocage" ] ; then
    LIB="/usr/local/lib/iocage"
else
    echo "ERROR: missing libraries" >&2
    exit 1
fi

# Source the libs needed to use the script
. "${LIB}/ioc-cmd"
. "${LIB}/ioc-globals"
. "${LIB}/ioc-info"
. "${LIB}/ioc-help"
. "${LIB}/ioc-common"
. "${LIB}/ioc-zfs"
. "${LIB}/ioc-send"
. "${LIB}/ioc-snapshot"
. "${LIB}/ioc-upgrade"
. "${LIB}/ioc-image"
. "${LIB}/ioc-common"
. "${LIB}/ioc-rc"
. "${LIB}/ioc-network"
. "${LIB}/ioc-rctl"
. "${LIB}/ioc-configure"
. "${LIB}/ioc-hacks"
. "${LIB}/ioc-git"

if [ -z "$1" ] ; then
    __usage
    exit 0
fi

if [ "$1" = "-v" ] ; then
    set -x
    shift
fi

if [ "$1" = "help" -o "$1" = "--help" -o "$1" = "-h" ] ; then
    __help
    exit 0
fi

if [ $(__readonly_cmd "$1") != "0" -a "$(whoami)" != "root" ] ; then
    echo "* The $1 command needs root credentials!" >&2
    exit 1
fi

# Work around zpool activation chicken-egg problem
# (when activating a pool don't look for an existing one)
# Also look for an altroot and if it exists change lib/ioc-globals to that value
if [ "$1" != "activate" -a "$1" != "deactivate" ] ; then
    __find_mypool
    __check_filesystems
fi

__parse_cmd "$@"
