#!/bin/sh

__update () {
  local _name _dataset _fulluuid _mountpoint _date _jail_type _non_interactive \
        _resolv _jail_release _jail_base

  _name=$2
  _resolv="0"

    # Start looking for any command switches, if nothing special is found
    # then proceed with the normal update procedure
    case "$1" in
        -n)
            _dataset=$(__find_jail $_name)
            _fulluuid="$(__check_name $_name)"
            _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
            _jail_type="$(__get_jail_prop type $_fulluuid)"

            # If a git jail is found, update the remote and show the user the
            # status output
            case $_jail_type in
                gitjail)
                    git -C $_mountpoint/_ remote update
                    git -C $_mountpoint/_ status -uno
                    ;;
            esac
            ;;
        -P|-p|--ports)
            if [ ! -e "${iocroot}/base/${_name}/root" ] ; then
                __die "${_name} does not exist!"
            fi

            mount -t devfs devfs ${iocroot}/base/${_name}/root/dev
            cat /etc/resolv.conf > \
                ${iocroot}/base/${_name}/root/etc/resolv.conf
            chroot ${iocroot}/base/${_name}/root \
                env UNAME_r="${_name}" env PAGER="/bin/cat" \
                portsnap --interactive fetch update
            umount ${iocroot}/base/${_name}/root/dev
            rm ${iocroot}/base/${_name}/root/etc/resolv.conf
            ;;
        *)
            shift 3
            _name=$1
            _dataset=$(__find_jail $_name)
            _fulluuid="$(__check_name $_name)"
            _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
            _date=$(date "+%F_%T")
            _jail_type="$(__get_jail_prop type $_fulluuid)"
            _jail_release="$(__get_jail_prop release $_fulluuid)"
            _jail_base="$(__get_jail_prop base ${_fulluuid})"

            # Check all jail types and do the right thing
            case $_jail_type in
                basejail)
                    if [ -e ${iocroot}/base/${_jail_base}/root/etc/freebsd-update.conf ] ; then
                        if [ ! -e ${iocroot}/base/${_jail_base}/root/etc/resolv.conf ] ; then
                            export _resolv="1"
                            cat /etc/resolv.conf > \
                            ${iocroot}/base/${_jail_base}/root/etc/resolv.conf
                        fi

                        mount -t devfs devfs \
                            ${iocroot}/base/${_jail_base}/root/dev

                        case "${_jail_base}" in
                            9.3-RELEASE | 10.1-RELEASE)
                                # Remove the interactive check in freebsd-update
                                sed 's/\[ ! -t 0 \]/false/' \
                                    ${iocroot}/base/${_jail_base}/root/usr/sbin/freebsd-update \
                                    > ${iocroot}/base/${_jail_base}/root/tmp/freebsd-update
                                chmod +x ${iocroot}/base/${_jail_base}/root/tmp/freebsd-update
                                chroot ${iocroot}/base/${_jail_base}/root \
                                    env UNAME_r="${_jail_base}" \
                                    env PAGER="/bin/cat" \
                                    /tmp/freebsd-update fetch
                                rm ${iocroot}/base/${_jail_base}/root/tmp/freebsd-update
                                ;;
                            *)
                                chroot ${iocroot}/base/${_jail_base}/root \
                                    env UNAME_r="${_jail_base}" \
                                    env PAGER="/bin/cat" \
                                    freebsd-update --not-running-from-cron fetch
                                ;;
                            esac

                        chroot ${iocroot}/base/${_jail_base}/root \
                            env UNAME_r="${_jail_base}" env PAGER="/bin/cat" \
                            freebsd-update install
                        umount ${iocroot}/base/${_jail_base}/root/dev

                        if [ "${_resolv}" = "1" ] ; then
                            if [ $? -eq 0 ] ; then
                                rm -f \
                                    ${iocroot}/base/${_jail_base}/root/etc/resolv.conf
                            fi
                        fi
                    fi
                    # Re-clone required filesystems
                    __reclone_basejail "${_fulluuid}" "${_dataset}"
                    __umount_basejail "${_fulluuid}"
                    echo "* ${_name} updated successfully"
                    ;;
                gitjail)
                    # Update the local git repo to the latest remote
                    git -C $_mountpoint/root pull
                    ;;
                *)
                    echo "* Creating back-out update snapshot."
                    __snapshot ${_fulluuid}@ioc-update_${_date}

                    # Override the release that freebsd-update uses and
                    # set the pager to cat so that it isn't interactive
                    echo "* Updating jail.."

                    # Migrate release property to base
                    if [ -z ${_jail_base} ] ; then
                        _jail_base="${_jail_release}"
                    fi

                    if [ -e ${iocroot}/base/${_jail_base}/root/etc/freebsd-update.conf ] ; then
                        if [ ! -e ${_mountpoint}/root/etc/resolv.conf ] ; then
                            export _resolv="1"
                            cat /etc/resolv.conf > \
                            ${_mountpoint}/root/etc/resolv.conf
                        fi

                        mount -t devfs devfs \
                            ${_mountpoint}/root/dev

                        case "${_jail_base}" in
                            9.3-RELEASE | 10.1-RELEASE)
                                # Remove the interactive check in freebsd-update
                                sed 's/\[ ! -t 0 \]/false/' \
                                    ${_mountpoint}/root/usr/sbin/freebsd-update \
                                    > ${_mountpoint}/root/tmp/freebsd-update
                                chmod +x ${_mountpoint}/root/tmp/freebsd-update
                                chroot ${_mountpoint}/root \
                                    env UNAME_r="${_jail_base}" \
                                    env PAGER="/bin/cat" \
                                    /tmp/freebsd-update fetch
                                rm ${_mountpoint}/root/tmp/freebsd-update
                                ;;
                            *)
                                chroot ${_mountpoint}/root \
                                    env UNAME_r="${_jail_base}" \
                                    env PAGER="/bin/cat" \
                                    freebsd-update --not-running-from-cron fetch
                                ;;
                            esac

                        chroot ${_mountpoint}/root \
                            env UNAME_r="${_jail_base}" env PAGER="/bin/cat" \
                            freebsd-update install
                        umount ${_mountpoint}/root/dev

                        if [ "${_resolv}" == "1" ] ; then
                            if [ $? -eq 0 ] ; then
                                rm -f ${_mountpoint}/root/etc/resolv.conf
                            fi
                        fi
                    fi

                    echo "* ${_name} updated successfully. Please reboot jail and inspect."
                    echo "* Remove:"
                    echo "    snapshot: ${_dataset}/root@ioc-update_${_date}"
                    echo "* if everything is OK."
                    ;;
            esac

            if [ -z $_name ] ; then
                __die "missing UUID!"
            fi

            if [ -z $_dataset ] ; then
                __die "$_name not found!"
            fi
            ;;
      esac
}

__upgrade () {
    local _name _base _fulluuid _jail_type _mountpoint _date _oldbase _resolv \
          _origin _date

    _name="$1"
    _base="$(uname -r|cut -f 1,2 -d'-'|sed -E 's/CURRENT.*|STABLE.*/RELEASE/')"
    _dataset="$(__find_jail ${_name})" || exit $?
    _fulluuid="$(__check_name ${_name})"
    _jail_type="$(__get_jail_prop type ${_fulluuid})"
    _mountpoint="$(__get_jail_prop mountpoint ${_fulluuid})"
    _oldbase="$(zfs get -H -o value org.freebsd.iocage:base ${_dataset})"
    _date=$(date "+%F")
    _resolv="0"

    if [ -z ${_name} ] ; then
        __die "missing UUID!"
    fi

    if [ -z ${_dataset} ] ; then
        __die "${_name} not found!"
    fi

    if [ -n "${iocset_base}" ] ; then
        _base="${iocset_base}"
    fi

    if [ ! -d ${iocroot}/base/${_base} ] ; then
        __error "${_base} not found!"
        echo "  Please run iocage fetch first." >&2
        exit 1
    fi

    # Migrate from release to base property
    if [ "${_oldbase}" = "-" ] ; then
        _oldbase="$(__get_jail_prop release ${_fulluuid} ${_dataset})"
        __set_jail_prop base="${_oldbase}" "${_fulluuid}"
    fi

    # If jail is a basejail then set the new release and reclone the datasets
    # back up /etc just in case the merge fails
    if [ ${_jail_type} = "basejail" ] ; then
        _jail_datasets="$(__find_jail ALL | \
                        grep -vE "${pool}/iocage/.defaults|${pool}/iocage/base/[0-9].?\>")"
        # Check to see if the jail has a stale upgrade snapshot.
        for _fs in ${_jail_datasets} ; do
            _snapcheck="$(zfs list -Ht snap | \
                     grep -E "${_fulluuid}.*ioc-upgrade" | \
                     awk '{print $1}')"
            if [ ! -z ${_snapcheck} ] ; then
                __error "${_name} has an existing upgrade snapshot" >&2
                printf "%1s ${_snapcheck} \n" >&2
                printf "%1s please remove this before trying to upgrade. \n" >&2
                exit 1
            fi
        done

        zfs set org.freebsd.iocage:base="${_base}" ${_dataset}
        __reclone_basejail ${_fulluuid}
        cp -Rp ${_mountpoint}/_/etc \
               ${_mountpoint}/_/etc.old
        zfs snapshot ${_dataset}/root@ioc-upgrade_${_date}

        # Check for zero exit code(success) otherwise bail and revert everything
        if [ $? -eq 0 ] ; then
            echo "* ${_name} upgraded successfully. Please reboot jail and inspect."
            echo "* Remove:"
            echo "    /etc backup: ${_mountpoint}/_/etc.old"
            echo "    snapshot: ${_dataset}/root@ioc-upgrade_${_date}"
            echo "* if everything is OK."
            __umount_basejail "${_fulluuid}"
            exit 0
        else
            echo "" >&2
            echo "* Upgrade failed! Backing out." >&2
            zfs set org.freebsd.iocage:base="${_oldbase}" ${_dataset}
            zfs rollback -rRf ${_dataset}/root@ioc-upgrade_${_date}
            zfs destroy ${_dataset}/root@ioc-upgrade_${_date}
            umount ${_mountpoint}/root/etc
            rm -rf ${_mountpoint}/_/etc
            mv ${_mountpoint}/_/etc.old \
               ${_mountpoint}/_/etc
            __reclone_basejail
            __umount_basejail "${_fulluuid}"
            exit 1
        fi
    elif [ ${_jail_type} = "thickjail" ] ; then
        # __spinner needs to be recreated here as we redirect with __update
        _spinner='/-\|'

        printf "* Updating ${_name} to latest patch level first:  "

        while true; do
            printf '\b%.1s' "${_spinner}"
            _spinner=${_spinner#?}${_spinner%???}
            sleep .1
        done &

        trap "kill $!" 2 3
        __update ${_fulluuid} > /dev/null 2>&1
        printf "\b%1s\n" "done!" ; kill $! && trap " " 2 3

        echo "* Creating back-out upgrade snapshot."
        zfs snapshot ${_dataset}/root@ioc-upgrade_${_date}
        echo "* Upgrading jail."
        if [ -e ${iocroot}/base/${_base}/root/etc/freebsd-update.conf ] ; then
            if [ ! -e ${_mountpoint}/root/etc/resolv.conf ] ; then
                export _resolv="1"
                cat /etc/resolv.conf > \
                    ${_mountpoint}/root/etc/resolv.conf
            fi
            mount -t devfs devfs \
                ${_mountpoint}/root/dev
            chroot ${_mountpoint}/root \
                env UNAME_r="${_oldbase}" env PAGER="/bin/cat" \
                freebsd-update -r ${_base} upgrade
            if [ $? -eq 0 ] ; then
                while [ $? -eq 0 ] ; do
                    chroot ${_mountpoint}/root \
                        env UNAME_r="${_oldbase}" env PAGER="/bin/cat" \
                        freebsd-update -r ${_base} install
                done
                if [ "${_resolv}" == "1" ] ; then
                    rm -f ${_mountpoint}/root/etc/resolv.conf
                fi
                umount ${_mountpoint}/root/dev
                # Set jail's zfs property to new release
                zfs set org.freebsd.iocage:base="${_base}" ${_dataset}
            else
                echo "* Upgrade failed, aborting install." >&2
                zfs rollback -rRf ${_dataset}/root@ioc-upgrade_${_date}
                zfs destroy ${_dataset}/root@ioc-upgrade_${_date}
                exit 1
            fi
        fi

        echo "* ${_name} upgraded successfully. Please reboot jail and inspect."
        echo "* Remove:"
        echo "    snapshot: ${_dataset}/root@ioc-upgrade_${_date}"
        echo "* if everything is OK."
    else
        __die "upgrade is not supported for this type of jail"
    fi
}
