#!/bin/sh

__update () {
  local _name _dataset _fulluuid _mountpoint _date _jail_type _non_interactive \
        _resolv

  _name=$2
  _resolv="0"

    # Start looking for any command switches, if nothing special is found
    # then proceed with the normal update procedure
    case "$1" in
        -n)
            _dataset=$(__find_jail $_name)
            _fulluuid="$(__check_name $_name)"
            _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
            _jail_type="$(__get_jail_prop type $_fulluuid)"

            # If a git jail is found, update the remote and show the user the
            # status output
            case $_jail_type in
                gitjail)
                    git -C $_mountpoint/_ remote update
                    git -C $_mountpoint/_ status -uno
                    ;;
            esac
            ;;
        *)
            shift 3
            _name=$1
            _dataset=$(__find_jail $_name)
            _fulluuid="$(__check_name $_name)"
            _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"
            _date=$(date "+%F_%T")
            _jail_type="$(__get_jail_prop type $_fulluuid)"
            _jail_release="$(__get_jail_prop release $_fulluuid)"

            # Check all jail types and do the right thing
            case $_jail_type in
                basejail)
                    if [ -e ${iocroot}/base/${base}/root/etc/freebsd-update.conf ] ; then
                        if [ ! -e ${iocroot}/base/${base}/root/etc/resolv.conf ] ; then
                            export _resolv="1"
                            cat /etc/resolv.conf > \
                            ${iocroot}/base/${base}/root/etc/resolv.conf
                        fi
                        mount -t devfs devfs \
                            ${iocroot}/base/${base}/root/dev
                        chroot ${iocroot}/base/${base}/root/ \
                            env UNAME_r="${base}" env PAGER="/bin/cat" \
                            freebsd-update --not-running-from-cron fetch
                        chroot ${iocroot}/base/${base}/root \
                            env UNAME_r="${base}" env PAGER="/bin/cat" \
                            freebsd-update install
                        umount ${iocroot}/base/${base}/root/dev
                        if [ "${_resolv}" = "1" ] ; then
                            if [ $? -eq 0 ] ; then
                                rm -f \
                                    ${iocroot}/base/${base}/root/etc/resolv.conf
                            fi
                        fi
                    fi
                    # Re-clone required filesystems
                    __reclone_basejail "${_fulluuid}" "${_dataset}"
                    __umount_basejail "${_fulluuid}"
                ;;
                gitjail)
                    # Update the local git repo to the latest remote
                    git -C $_mountpoint/root pull
                    ;;
                *)
                    echo "* Creating back-out update snapshot."
                    __snapshot ${_fulluuid}@ioc-update_${_date}

                    # Override the release that freebsd-update uses and
                    # set the pager to cat so that it isn't interactive
                    echo "* Updating jail.."

                    if [ ${base} != ${_jail_release} ] ; then
                        base="${_jail_release}"
                    fi

                    if [ -e ${iocroot}/base/${base}/root/etc/freebsd-update.conf ] ; then
                        if [ ! -e ${_mountpoint}/root/etc/resolv.conf ] ; then
                            export _resolv="1"
                            cat /etc/resolv.conf > \
                            ${_mountpoint}/root/etc/resolv.conf
                        fi
                        mount -t devfs devfs \
                            ${_mountpoint}/root/dev
                        chroot ${_mountpoint}/root \
                            env UNAME_r="${base}" env PAGER="/bin/cat" \
                            freebsd-update --not-running-from-cron fetch
                        chroot ${_mountpoint}/root \
                            env UNAME_r="${base}" env PAGER="/bin/cat" \
                            freebsd-update install
                        umount ${_mountpoint}/root/dev
                        if [ "${_resolv}" == "1" ] ; then
                            if [ $? -eq 0 ] ; then
                                rm -f ${_mountpoint}/root/etc/resolv.conf
                            fi
                        fi
                    fi

                    echo "* ${_name} updated successfully. Please reboot jail and inspect."
                    echo "* Remove:"
                    echo "    snapshot: ${_dataset}/root@ioc-update_${_date}"
                    echo "* if everything is OK."
                    ;;
            esac

            if [ -z $_name ] ; then
                __die "missing UUID!"
            fi

            if [ -z $_dataset ] ; then
                __die "$_name not found!"
            fi
            ;;
      esac
}

__upgrade () {
    local _name _fulluuid _jail_type _jail_release _mountpoint _date \
          _oldrelease _resolv

    _name="$1"
    _dataset="$(__find_jail ${_name})" || exit $?
    _fulluuid="$(__check_name ${_name})"
    _jail_type="$(__get_jail_prop type ${_fulluuid})"
    _mountpoint="$(__get_jail_prop mountpoint ${_fulluuid})"
    _oldrelease="$(zfs get -H -o value org.freebsd.iocage:release ${_dataset})"
    _resolv="0"

    if [ -z ${_name} ] ; then
        __die "missing UUID!"
    fi

    if [ -z ${_dataset} ] ; then
        __die "${_name} not found!"
    fi

    if [ ! -d ${iocroot}/base/${base} ] ; then
        __error "${base} not found!"
        echo "  Please run iocage fetch first." >&2
        exit 1
    fi

    # If jail is a basejail then set the new release and reclone the datasets
    # also backup jail's /etc just in-case etcupdate doesn't go as planned
    if [ ${_jail_type} == "basejail" ] ; then
        zfs set org.freebsd.iocage:release="${base}" ${_dataset}
        __reclone_basejail ${_fulluuid}
        cp -Rp ${_mountpoint}/_/etc \
               ${_mountpoint}/_/etc.old
        zfs snapshot ${_dataset}/root@ioc-upgrade_$(date +%F)

        # Check for zero exit code(success) otherwise bail and revert everything
        if [ $? -eq 0 ] ; then
            echo ""
            echo "* Upgrade successful. Please restart jail and inspect."
            echo "* Remove:"
            echo "    etc backup: ${_mountpoint}/_/etc.old"
            echo "    snapshot: ${_dataset}/root@ioc-upgrade_$(date +%F)"
            echo "* if everything is OK."
            __umount_basejail "${_fulluuid}"
            exit 0
        else
            echo "" >&2
            echo "* Upgrade failed! Backing out." >&2
            zfs set org.freebsd.iocage:release="${_oldrelease}" ${_dataset}
            zfs rollback -rRf ${_dataset}/root@ioc-upgrade_$(date +%F)
            zfs destroy ${_dataset}/root@ioc-upgrade_$(date +%F)
            umount ${_mountpoint}/root/etc
            rm -rf ${_mountpoint}/_/etc
            mv ${_mountpoint}/_/etc.old \
               ${_mountpoint}/_/etc
            __reclone_basejail
            __umount_basejail "${_fulluuid}"
            exit 1
        fi
    elif [ ${_jail_type} == "thickjail" ] ; then
        echo "* Updating jail to latest patch level first."
        __update ${_fulluuid}
        # The update routine sets this to the old RELEASE, setting it back
        unset release
        release=$(uname -r|cut -f 1,2 -d'-')
        echo "* Creating back-out upgrade snapshot."
        zfs snapshot ${_dataset}/root@ioc-upgrade_$(date +%F)
        echo "* Upgrading jail."

        if [ -e ${iocroot}/base/${base}/root/etc/freebsd-update.conf ] ; then
            if [ ! -e ${_mountpoint}/root/etc/resolv.conf ] ; then
                export _resolv="1"
                cat /etc/resolv.conf > \
                    ${_mountpoint}/root/etc/resolv.conf
            fi
            mount -t devfs devfs \
                ${_mountpoint}/root/dev
            chroot ${_mountpoint}/root \
                env UNAME_r="${_oldrelease}" env PAGER="/bin/cat" \
                freebsd-update -r ${base} upgrade
            if [ $? -eq 0 ] ; then
                while [ $? -eq 0 ] ; do
                    chroot ${_mountpoint}/root \
                        env UNAME_r="${_oldrelease}" env PAGER="/bin/cat" \
                        freebsd-update -r ${base} install
                done
                if [ "${_resolv}" == "1" ] ; then
                    rm -f ${_mountpoint}/root/etc/resolv.conf
                fi
                umount ${_mountpoint}/root/dev
                # Set jail's zfs property to new release
                zfs set org.freebsd.iocage:release="${base}" ${_dataset}
            else
                echo "* Upgrade failed, aborting install." >&2
                zfs rollback -rRf ${_dataset}/root@ioc-upgrade_$(date +%F)
                zfs destroy ${_dataset}/root@ioc-upgrade_$(date +%F)
                exit 1
            fi
        fi

        echo "* ${_name} upgraded successfully. Please reboot jail and inspect."
        echo "* Remove:"
        echo "    snapshot: ${_dataset}/root@ioc-upgrade_${_date}"
        echo "* if everything is OK."
    else
        __die "upgrade is not supported for this type of jail"
    fi
}
