#!/bin/sh

# activate pool for iocage
# intended for automation tool
__activate () {
    local _pool
    _pool="$1"

    if [ ! -z ${_pool} ] ; then
        zpool set comment=iocage ${_pool}
    else
        __find_mypool
        echo "pool: ${pool}"
    fi

    exit 0
}

__deactivate () {
    local _pool
    _pool="$1"

    if [ ! -z ${_pool} ] ; then
        zpool set comment=inherit ${_pool}
    fi

    exit 0
}

__clean () {
    local _answer _base_exists _jail_type

    # Look for the right switch and then ask the user if they are sure
    case "$1" in
        -a)
            echo " "
            echo "  WARNING: this will destroy ${pool}/iocage"
            echo " "
            echo -n "  Are you sure ? y[N]: "
            read _answer

            if [ "${_answer}" == "Y" -o "${_answer}" == "y" ] ; then
                __stop_jail_all > /dev/null 2>&1
                if [ $? -eq 0 ] ; then
                    __spinner "  INFO: destroying ${pool}/iocage:  " \
                              "zfs destroy -rRf ${pool}/iocage"
                    rm -rf ${iocroot}
                    exit 0
                else
                    __die "some jails were unable to be stopped."
                fi
            else
                __die "command not confirmed.  no action taken."
            fi
        ;;
        -b)
            echo " "
            echo "  WARNING: this will destroy all bases and basejails"
            echo " "
            echo -n "  Are you sure ? y[N]: "
            read _answer

            if [ "${_answer}" == "Y" -o "${_answer}" == "y" ] ; then
                __clean_basejail
                if [ $? -eq 0 ] ; then
                    __spinner "  INFO: destroying ${pool}/iocage/download:  " \
                              "zfs destroy -rRf ${pool}/iocage/download"
                    __spinner "  INFO: destroying ${pool}/iocage/base:  " \
                              "zfs destroy -rRf ${pool}/iocage/base"
                    exit 0
                else
                    __die "some jails were unable to be stopped."
                fi
            else
                __die "command not confirmed.  no action taken."
            fi
        ;;
        -j)
            echo " "
            echo "  WARNING: this will destroy all jails"
            echo " "
            echo -n "  Are you sure ? y[N]: "
            read _answer

            if [ "${_answer}" == "Y" -o "${_answer}" == "y" ] ; then
                __clean_snapshots
                __stop_jail_all > /dev/null 2>&1
                if [ $? -eq 0 ] ; then
                    __spinner "  INFO: destroying ${pool}/iocage/jails:  " \
                              "zfs destroy -rRf ${pool}/iocage/jails"
                    __spinner "  INFO: cleaning TAGs at ${pool}/iocage/tags:  " \
                              "rm -rf ${iocroot}/tags"
                    exit 0
                else
                    __die "some jails were unable to be stopped."
                fi
            else
                __die "command not confirmed.  no action taken."
            fi
        ;;
    esac
}

__clean_basejail () {
    local _jails _juuid _jail_type
    _jails=$(__find_jail ALL | \
           grep -vE "${pool}/iocage/.defaults|${pool}/iocage/base/[0-9].?\>")

    for _jail in ${_jails} ; do
        _juuid="$(zfs get -H -o value org.freebsd.iocage:host_hostuuid \
                ${_jail})"
        _jail_type="$(__get_jail_prop type ${_juuid} 2> /dev/null)"
        if [ "${_jail_type}" == "basejail" ] ; then
            __destroy_jail "-f" "${_juuid}" > /dev/null 2>&1
        fi
    done

    return $?
}

__clean_snapshots () {
    local _snapshots

    _snapshots="$(zfs list -Hrt snapshot -o name ${pool}/iocage)"
    for _snap in $(echo ${_snapshots}) ; do
        zfs destroy -rR ${_snap} > /dev/null 2>&1
    done
}

# Accepts two arguments. Which is used as the UUID for the umount operations
# and what release to use.
__migrate_basejail () {
    local _bfs_list _fulluuid _base _release_dataset _release_dataset_check

    _fulluuid="$1"
    _base="$2"
    _bfs_list="bin
               boot
               lib
               libexec
               rescue
               sbin
               usr"
    _release_dataset="${pool}/iocage/releases"
    _release_dataset_check="$(zfs get -H creation ${_release_dataset} > \
                           /dev/null 2>&1 ; echo $?)"

    # Check to see if the user has the old style of RELEASE datasets
    if [ "${_release_dataset_check}" = "0" ] ; then
        zfs rename -f "${pool}/iocage/base" \
                      "${pool}/iocage/base_old"
        zfs inherit -r mountpoint "${_release_dataset}"
        zfs rename -f "${_release_dataset}" \
                      "${pool}/iocage/base"
    fi

    # Set up all the new stuff
    mkdir ${iocroot}/jails/${_fulluuid}/_
    mkdir ${iocroot}/jails/${_fulluuid}/_/usr

    # Create these dirs for old RELEASEs fetched for the basejail
    # Silencing in case they exist, nobody cares.
    mkdir ${iocroot}/base/${_base}/root/usr/home  > /dev/null 2>&1
    cd ${iocroot}/base/${_base}/root && ln -s usr/home home 2>&1
    mkdir ${iocroot}/base/${_base}/root/compat  > /dev/null 2>&1
    mkdir ${iocroot}/base/${_base}/root/usr/ports > /dev/null 2>&1

    # If the user has a /usr/local, move it for migration
    if [ -e "${iocroot}/jails/${_fulluuid}/root/usr/local" ] ; then
        if [ ! -z "$(ls -A ${iocroot}/jails/${_fulluuid}/root/usr/local)" ] ; then
            mv    ${iocroot}/jails/${_fulluuid}/root/usr/local \
                  ${iocroot}/jails/${_fulluuid}/_/usr/local
        else
            mkdir ${iocroot}/jails/${_fulluuid}/_/usr/local
        fi
    fi

    # If the user had a ports tree, move it for migration
    if [ -e "${iocroot}/jails/${_fulluuid}/root/usr/ports" ] ; then
        if [ ! -z "$(ls -A ${iocroot}/jails/${_fulluuid}/root/usr/ports)" ] ; then
            mv    ${iocroot}/jails/${_fulluuid}/root/usr/ports \
                  ${iocroot}/jails/${_fulluuid}/_/usr/ports
        else
            mkdir ${iocroot}/jails/${_fulluuid}/_/usr/ports
        fi
    fi

    # If the user had a compat directory, move it for migration
    if [ -e "${iocroot}/jails/${_fulluuid}/root/compat" ] ; then
        if [ ! -z "$(ls -A ${iocroot}/jails/${_fulluuid}/root/compat)" ] ; then
            mv    ${iocroot}/jails/${_fulluuid}/root/compat \
                  ${iocroot}/jails/${_fulluuid}/_/compat
        else
            mkdir ${iocroot}/jails/${_fulluuid}/_/compat
        fi
    fi

    # If the user had a usr/obj directory, move it for migration
    if [ -e "${iocroot}/jails/${_fulluuid}/root/usr/obj" ] ; then
        if [ ! -z "$(ls -A ${iocroot}/jails/${_fulluuid}/root/usr/obj)" ] ; then
            mv    ${iocroot}/jails/${_fulluuid}/root/compat \
                  ${iocroot}/jails/${_fulluuid}/_/compat
        else
            mkdir ${iocroot}/jails/${_fulluuid}/_/compat
        fi
    fi

    # Move all the r/w required mountpoints for migration
    mv    ${iocroot}/jails/${_fulluuid}/root/etc \
          ${iocroot}/jails/${_fulluuid}/_/etc
    mv    ${iocroot}/jails/${_fulluuid}/root/root \
          ${iocroot}/jails/${_fulluuid}/_/root
    mv    ${iocroot}/jails/${_fulluuid}/root/usr/home \
          ${iocroot}/jails/${_fulluuid}/_/usr/home
    mv    ${iocroot}/jails/${_fulluuid}/root/var \
          ${iocroot}/jails/${_fulluuid}/_/var
    zfs   umount -f ${pool}/iocage/jails/${_fulluuid}/root

    # Destroy all the old datasets now
    for _fs in ${_bfs_list} ; do
        zfs destroy -rf ${pool}/iocage/jails/${_fulluuid}/root/${_fs}
    done
}

__reclone_basejail () {
    local _fulluuid _fs_list _dataset _jail_base _jailed_dataset \
          _jailed_dataset_check _jail_datasets _base_inuse _origin _tag _uuid \
          _jail_mount _hack88 _shortuuid _inherit_props

    _fulluuid="$1"
    _dataset="$2"
    _jail_base="$(__get_jail_prop base ${_fulluuid} ${_dataset})"
    _fs_list="$(zfs list -t snap -rH -o name ${pool}/iocage/base | \
             grep root@${_fulluuid})"
    _old_base_check="$(zfs list -Hr ${pool}/iocage/jails/${_fulluuid} | \
                     grep -v data | wc -l)"
    _jailed_dataset="${pool}/iocage/jails/${_fulluuid}/root/data"
    _jail_tag="$(__get_jail_prop tag ${_fulluuid} ${_dataset})"
    _jail_mount="$(__get_jail_prop mountpoint ${_fulluuid} ${_dataset})"
    _hack88="$(__get_jail_prop hack88 ${_fulluuid} ${_dataset})"
    _shortuuid="$(echo ${_fulluuid}|cut -f1 -d\-)"
    _jailed_dataset_check="$(zfs get -H creation ${_jailed_dataset} > \
                           /dev/null 2>&1 ; echo $?)"
    _inherit_props="$(__unset_inherited ${_fulluuid})"


    # Check to see if the user has the old style of jailed datasets
    if [ "${_jailed_dataset_check}" = "0" ] ; then
        zfs set jailed=off "${_jailed_dataset}"
        zfs rename -f "${_jailed_dataset}" \
                      "${pool}/iocage/jails/${_fulluuid}/data"
        zfs set jailed=on "${pool}/iocage/jails/${_fulluuid}/data"
    fi

    # Migrate from release to base property
    if [ "${_jail_base}" = "none" ] ; then
        _old_jail_release="$(__get_jail_prop release ${_fulluuid} ${_dataset})"
        __set_jail_prop base="${_old_jail_release}" "${_fulluuid}"
        unset _jail_base
        _jail_base="$(__get_jail_prop base ${_fulluuid} ${_dataset})"
    fi

    # If the length is over this, it's an old-style basejail
    if [ "${_old_base_check}" -gt "15" ] ; then
        __migrate_basejail "${_fulluuid}" "${_jail_base}"
    fi

    # Look for hack88, if it exists, pass the short uuid
    if [ "${_hack88}" = "1" ] ; then
        __umount_basejail "${_shortuuid}"
    else
        __umount_basejail "${_fulluuid}"
    fi

    zfs destroy -f ${pool}/iocage/jails/${_fulluuid}/root > /dev/null 2>&1

    if [ $? -eq 1 ] ; then
        _jail_datasets="$(__find_jail ALL | \
                        grep -vE "${pool}/iocage/.defaults|${pool}/iocage/base/[0-9].?\>|${pool}/iocage/releases")"
        for _fs in ${_jail_datasets} ; do
            _origin="$(zfs get -H -o value origin ${_fs} | cut -f1 -d@)"
            _tag="$(zfs get -H -o value org.freebsd.iocage:tag ${_fs})"
            _uuid="$(zfs get -H -o value org.freebsd.iocage:host_hostuuid ${_fs})"

            if [ "${_origin}" = "${_dataset}" ] ; then
                __info "jail has dependent clone, uuid: ${_uuid} (${_tag})"
            fi
        done
        __info "${_jail_tag} will not be up to date with base: ${_jail_base}"
    else
        # Destroy the old datasets
        for _fs in ${_fs_list} ; do
            zfs destroy -f ${_fs} > /dev/null 2>&1
        done
        # Set up the new RELEASE root dataset to be cloned from
        zfs snapshot ${pool}/iocage/base/${_jail_base}/root@${_fulluuid}

        # Recloning the root dataset and remounting the children
        eval "zfs clone -o readonly=on ${_inherit_props} \
            \"${pool}/iocage/base/${_jail_base}/root@${_fulluuid}\" \
            \"${pool}/iocage/jails/${_fulluuid}/root\""
    fi

    # Make sure the usr/home directory exists in the RELEASE
    if [ ! -e "${iocroot}/base/${_jail_base}/root/usr/home" ] ; then
        mkdir ${iocroot}/base/${_jail_base}/root/usr/home
        cd ${iocroot}/base/${_jail_base}/root && ln -s usr/home home 2>&1
    fi

    # Make sure the /compat directory exists in the RELEASE
    if [ ! -e "${iocroot}/base/${_jail_base}/root/compat" ] ; then
        mkdir ${iocroot}/base/${_jail_base}/root/compat
    fi

    # Make sure the /var/ports directory exists in the basejail overlay
    # if needed
    if [ -e "${iocroot}/base/${_jail_base}/root/var/ports" ] ; then
        if [ "${_hack88}" = "1" ] ; then
            if [ ! -e "${iocroot}/jails/${_shortuuid}/_/var/ports" ] ; then
                mkdir ${iocroot}/jails/${_shortuuid}/_/var/ports
                mkdir ${iocroot}/jails/${_shortuuid}/_/var/ports/distfiles
                mkdir ${iocroot}/jails/${_shortuuid}/_/var/ports/packages
            fi
        else
            if [ ! -e "${iocroot}/jails/${_fulluuid}/_/var/ports" ] ; then
                mkdir ${iocroot}/jails/${_fulluuid}/_/var/ports
                mkdir ${iocroot}/jails/${_fulluuid}/_/var/ports/distfiles
                mkdir ${iocroot}/jails/${_fulluuid}/_/var/ports/packages
            fi
        fi
    fi

    # Make sure the /usr/obj directory exists in the basejail overlay
    if [ ! -e "${iocroot}/jails/${_fulluuid}/_/usr/obj" ] ; then
        if [ "${_hack88}" = "1" ] ; then
            mkdir ${iocroot}/jails/${_shortuuid}/_/usr/obj
        else
            mkdir ${iocroot}/jails/${_fulluuid}/_/usr/obj
        fi
    fi

    # Look for hack88, if it exists, pass the short uuid
    if [ "${_hack88}" = "1" ] ; then
        __mount_basejail "${_shortuuid}"
    else
        __mount_basejail "${_fulluuid}"
    fi
}

# This creates jails----------------------------------------------------
__create_jail () {
    local _installed _releases _zfsconfig _supported_release _configured \
          _pname _prop _isprop _inherit_props _jail_zfs_mountpoint

    _installed=$(zfs list -rH ${pool}/iocage/base | grep ${base})
    _releases=$(__list_jails -r | grep -v "Downloaded releases:")
    _supported_release=$(echo "${base}" | grep "RELEASE")
    _devfs_string="$(grep -Fxq \
                  "## IOCAGE -- Add DHCP to ruleset 4" /etc/devfs.rules \
                  ; echo $?)"
    _base_inuse="$(zfs get -rH -o value origin ${pool} | \
                 grep ${pool}/iocage/base_old > /dev/null 2>&1 ; echo $?)"
    _release_dataset="${pool}/iocage/releases"
    _release_dataset_check="$(zfs get -H creation ${_release_dataset} > \
                           /dev/null 2>&1 ; echo $?)"
    _configured="0"

    if [ -z "${_supported_release}" -a "${2}" != "-e" -a "${1}" = "create" -a -z "${_installed}" ] ; then
        echo "  You are not running a production RELEASE. (${base})" >&2
        echo "  ERROR: Please specify base=RELEASE." >&2
        exit 1
    fi

    if [ -z "${_installed}" -a -z "${_releases}" -a "${2}" != "-e" ] ; then
        __die "no RELEASEs found locally, run iocage fetch first."
    elif [ -z "${_installed}" -a "${2}" != "-e" -a "${1}" != "-g" ] ; then
        echo "  RELEASE ${base} not found locally." >&2
        echo "  Please fetch ${base}" >&2
        echo "" >&2

        echo "  These are the RELEASEs you have already fetched:" >&2
        printf "${_releases}\n" >&2
        exit 1
    fi

    # Check to see if the user has the old style of RELEASE datasets
    if [ "${_release_dataset_check}" = "0" ] ; then
        zfs rename -f "${pool}/iocage/base" \
                      "${pool}/iocage/base_old"
        zfs inherit -r mountpoint "${_release_dataset}"
        zfs rename -f "${_release_dataset}" \
                      "${pool}/iocage/base"
    fi

    # Check to see if the old ${pool}/iocage/base datasets are needed any longer
    if [ "${_base_inuse}" = "1" ] ; then
        zfs destroy -r ${pool}/iocage/base_old > /dev/null 2>&1
    fi

    # Remove this as we only needed it to skip the checks for plugins
    if [ "${1}" = "-g" ] ; then
        shift 2
    fi

    _isprop="$(echo ${2} | awk 'BEGIN { FS = "=" } ; { print $2 }')"

    # Look for null output, if it is, then no property is following create
    if [ "${2}" != "-e" -a ! -z "${2}" ] ; then
        if [ ! "${_isprop}" ] ; then
            __die "invalid switch ${2}"
        else
            for _p in "$@" ; do
                if [ "$(echo $_p | grep -e ".*=.*")" ] ; then
                    _pname="$(echo ${_p} | \
                            awk 'BEGIN { FS = "=" } ; { print $1 }')"
                    if [ "${_pname}" = "release" ] ; then
                        __die "please replace release= with base="
                    fi
                fi
            done
        fi
    fi

    if [ "${2}" = "-e" ] ; then
        # Look to see if the jail type is our default, otherwise let the type
        # be whatever the user wants, it does not matter for an empty jail.
        if [ "${type}" = "basejail" ] ; then
            type=emptyjail
        fi

        _zfsconfig="$(__configure_jail generate)"
        eval "zfs create -p ${_zfsconfig} \"${pool}/iocage/jails/${uuid}\""
        zfs create -p ${pool}/iocage/jails/${uuid}/root
        _configured="1"
    else
        # Clones the root dataset from the RELEASE and makes sure to configure
        # the properties on it.
        _fs_list=$(zfs list -rH -o name ${pool}/iocage/base/${base})
        zfs snapshot ${pool}/iocage/base/${base}/root@${uuid}
        _zfsconfig="$(__configure_jail generate)"
        for _fs in ${_fs_list} ; do
            _cfs=$(echo ${_fs} | sed s#/base/${base}#/jails/${uuid}#g)
            if [ "${_cfs}" = "${pool}/iocage/jails/${uuid}/root" ] ; then
                eval "zfs clone -o readonly=on ${_inherit_props} \
                    \"${_fs}@${uuid}\" \"${_cfs}\""
            else
                eval "zfs create ${_zfsconfig} \"${pool}/iocage/jails/${uuid}\""
                _inherit_props="$(__unset_inherited ${uuid})"
            fi
        done

        # Create all the unionfs r/w directories needed
        mkdir  -p ${iocroot}/jails/${uuid}/_/compat
        mkdir     ${iocroot}/jails/${uuid}/_/etc
        mkdir     ${iocroot}/jails/${uuid}/_/root
        mkdir     ${iocroot}/jails/${uuid}/_/var
        mkdir  -p ${iocroot}/jails/${uuid}/_/usr/local
        mkdir     ${iocroot}/jails/${uuid}/_/usr/ports
        mkdir     ${iocroot}/jails/${uuid}/_/usr/home
        mount  -t unionfs -o noatime,copymode=transparent \
                  ${iocroot}/jails/${uuid}/_/etc/ \
                  ${iocroot}/jails/${uuid}/root/etc
        if [ -e "/etc/localtime" ] ; then
            cp /etc/localtime ${iocroot}/jails/${uuid}/_/etc/
        fi

        _configured="1"
    fi

    # create tag link
    __link_tag ${pool}/iocage/jails/${uuid}

    # remove any residual clone snapshots carried over from the RELEASE datasets
    __snapremove ${uuid}@ALL ${pool}/iocage/jails/${uuid}

    touch ${iocroot}/jails/${uuid}/fstab

    # Make sure the jail isn't a empty jail
    if [ "${2}" = "-e" ] ; then
        echo ${uuid}
        return 0
    fi

    # at create time set the default rc.conf
    if [ -e "${iocroot}/jails/${uuid}/root/etc/rc.conf" ] ; then
        sed -i '' "1s/hostname=.*/hostname=\"${host_hostname}\"/" \
            ${iocroot}/jails/${uuid}/root/etc/rc.conf
    else
        echo "hostname=\"${host_hostname}\"" > \
            ${iocroot}/jails/${uuid}/root/etc/rc.conf
        __jail_rc_conf >> \
            ${iocroot}/jails/${uuid}/root/etc/rc.conf
    fi

    if [ ! -e "${iocroot}/jails/${uuid}/root/etc/resolv.conf" ] ; then
        __resolv_conf ${uuid} ${pool}/iocage/jails/${uuid} > \
            ${iocroot}/jails/${uuid}/root/etc/resolv.conf
    fi

    for _prop in "$@" ; do
        _pname="$(echo ${_prop} | awk 'BEGIN { FS = "=" } ; { print $1 }')"
        # Look to see if the user wants a jailed dataset,
        # if they do then create it
        if [ "${_pname}" = "jail_zfs" ] ; then
            if [ ! -z "${iocset_jail_zfs_mountpoint}" ] ; then
                _jail_zfs_mountpoint="${iocset_jail_zfs_mountpoint}"
            else
                _jail_zfs_mountpoint="${jail_zfs_mountpoint}"
            fi

            eval "zfs create -u -o compression=lz4 \
                 -o mountpoint=${_jail_zfs_mountpoint} \
                 -o jailed=on ${_inherit_props} \"${pool}/${jail_zfs_dataset}\""
        # Do they want bpf exposed?
        elif [ "${_pname}" = "bpf" ] ; then
            if [ "${_devfs_string}" != "0" ] ; then
                __bpf_devfs >> /etc/devfs.rules
                service devfs restart > /dev/null 2>&1
            fi

            # Set the right devfs ruleset for DHCP/BPF.
            zfs set org.freebsd.iocage:devfs_ruleset=5 \
                ${pool}/iocage/jails/${uuid}
        fi
    done

    # configure the jail mountpoint
    __hack88_mount ${uuid} ${pool}/iocage/jails/${uuid}

    # Install extra packages
    # this requires working resolv.conf in jail
    if [ "${pkglist}" != "none" ] ; then
        # Mount all the filesytems needed to properly install pkg's
        # in a basejail
        mount -t tmpfs tmpfs ${iocroot}/jails/${uuid}/root/tmp
        mount -t devfs devfs ${iocroot}/jails/${uuid}/root/dev
        mount -t unionfs -o noatime,copymode=transparent \
                 ${iocroot}/jails/${uuid}/_/usr/local/ \
                 ${iocroot}/jails/${uuid}/root/usr/local
        mount -t unionfs -o noatime,copymode=transparent \
                 ${iocroot}/jails/${uuid}/_/var/ \
                 ${iocroot}/jails/${uuid}/root/var
        mount -t unionfs -o noatime,copymode=transparent \
                 ${iocroot}/jails/${uuid}/_/compat/ \
                 ${iocroot}/jails/${uuid}/root/compat

        __pkg_install "${iocroot}/jails/${uuid}/root"
        __umount_basejail "${uuid}"
    fi

    __umount_basejail "${uuid}"
    echo "  Successfully created: ${uuid} (${tag})"

    if [ ! -z "${start}" ] ; then
        __start_jail "${uuid}" "${pool}/iocage/jails/${uuid}"
    fi
}

# Cloning jails ----------------------------------------------------------
__clone_jail () {
    local  _name _snapshot _dataset _fs _fs_list _zfsconfig  _cfs _pname _prop \
           _isprop _inherit_props

    _name="$(echo $1 |  awk 'BEGIN { FS = "@" } ; { print $1 }')"
    _snapshot="$(echo $1 |  awk 'BEGIN { FS = "@" } ; { print $2 }')"
    _isprop="$(echo ${1} | awk 'BEGIN { FS = "=" } ; { print $2 }')"

    if [ ! -z "${_name}" -a ! -z "${_isprop}" ] ; then
        __die "please specify UUID or TAG before any properties"
    fi

    if [ -z "${_name}" ] ; then
        __die "missing UUID or TAG!"
    fi

    _fulluuid="$(__check_name ${_name})"
    _dataset="$(__find_jail ${_name})" || exit $?

    if [ -z ${_dataset} ] ; then
        exit 1
    fi

    _fs_list="$(zfs list -rH -o name ${_dataset})"
    _zfsconfig="$(__configure_jail generate)"

    # Snapshot if they don't have one and then clone the target jail
    if [ -z "${_snapshot}" ] ; then
        zfs snapshot -r ${_dataset}@${uuid}
        for _fs in ${_fs_list} ; do
            _cfs="$(echo ${_fs} | \
                 sed s#${_dataset}#${pool}/iocage/jails/${uuid}#g)"
            eval "zfs clone -p ${_zfsconfig} \"${_fs}@${uuid}\" \"${_cfs}\""
            # See if they had a jailed dataset before
            if [ $(echo ${_cfs} | grep data$ | wc -l) -eq 1 ] ; then
                zfs clone -o mountpoint=none -o jailed=on ${_fs}@${uuid} ${_cfs}
            fi
        done
    else
        for _fs in ${_fs_list} ; do
            _cfs="$(echo ${_fs} | \
                 sed s#${_dataset}#${pool}/iocage/jails/${uuid}#g)"

            if [ "${_cfs}" = "${pool}/iocage/jails/${uuid}/root" ] ; then
                eval "zfs clone ${_inherit_props} \
                    \"${_fs}@${uuid}\" \"${_cfs}\""
            elif [ "${_cfs}" = "${pool}/iocage/jails/${uuid}" ] ; then
                eval "zfs create ${_zfsconfig} \"${pool}/iocage/jails/${uuid}\""
                _inherit_props="$(__unset_inherited ${uuid})"
            fi

            # See if they had a jailed dataset before
            if [ $(echo ${_cfs} | grep data$ | wc -l) -eq 1 ] ; then
                zfs clone -o mountpoint=none -o jailed=on ${_fs}@${_snapshot} \
                    ${_cfs}
            fi
        done
    fi

    __link_tag ${pool}/iocage/jails/${uuid}

    # Check if fstab already exists otherwise create it
    if [ -e ${iocroot}/jails/${uuid}/fstab ] ; then
        mv ${iocroot}/jails/${uuid}/fstab \
           ${iocroot}/jails/${uuid}/fstab.${_name}
        touch ${iocroot}/jails/${uuid}/fstab
    else
        touch ${iocroot}/jails/${uuid}/fstab
    fi

    # Check if rc.conf already exists otherwise create it
    if [ -e ${iocroot}/jails/${uuid}/root/etc/rc.conf ] ; then
        cat ${iocroot}/jails/${uuid}/root/etc/rc.conf | \
        sed -E "s/[a-zA-Z0-9]{8,}-.*-.*-.*-[a-zA-Z0-9]{12,}/${uuid}/g" \
            > ${iocroot}/jails/${uuid}/rc.conf
        mv ${iocroot}/jails/${uuid}/rc.conf \
           ${iocroot}/jails/${uuid}/root/etc/rc.conf
    else
        echo "hostname=\"${host_hostname}\"" > \
            ${iocroot}/jails/${uuid}/root/etc/rc.conf
        __jail_rc_conf >> \
            ${iocroot}/jails/${uuid}/root/etc/rc.conf
    fi

    # Check if localtime already exists otherwise create it
    if [ -e "/etc/localtime" -a ! -e "${iocroot}/jails/${uuid}/root/etc/localtime" ] ; then
        cp /etc/localtime ${iocroot}/jails/${uuid}/root/etc/
    fi

    # Check if resolv.conf already exists otherwise create it
    if [ ! -e ${iocroot}/jails/${uuid}/root/etc/resolv.conf ] ; then
        __resolv_conf ${uuid} ${pool}/iocage/jails/${uuid} > \
            ${iocroot}/jails/${uuid}/root/etc/resolv.conf
    fi

    # configure the jail mountpoint
    __hack88_mount ${uuid} ${pool}/iocage/jails/${uuid}
    __set_jail_prop type=clonejail ${uuid} ${pool}/iocage/jails/${uuid}
    echo "  Successfully created: ${uuid} (${tag})"

    if [ ! -z "${start}" ] ; then
        __start_jail "${uuid}" "${pool}/iocage/jails/${uuid}"
    fi
}

# Destroy jails --------------------------------------------------------------
__destroy_jail () {
    local _name _answer _uuid_list _force _dataset _origin \
          _fulluuid _jail_path _state

    if [ -z "$1" ] ; then
        __die "missing UUID!"
    fi

    _name="$1"

    if [ "${_name}" = "ALL" ] ; then
        __die "please use iocage clean -j instead."
    fi

    _fulluuid_dataset="$(__get_uuid_and_dataset ${_name})" || exit $?

    set ${_fulluuid_dataset}
    _fulluuid="$1"
    _dataset="$2"

    if [ -z ${_dataset} ] ; then
        __die "${_name} not found!"
    fi

    __check_children ${_dataset}

    _origin="$(zfs get -H -o value origin ${_dataset})"
    _jail_path="$(__get_jail_prop mountpoint ${_fulluuid} ${_dataset})"
    _state="$(__is_running ${_fulluuid})"
    _jail_type="$(__get_jail_prop type ${_fulluuid} ${_dataset})"

    __check_children ${_fulluuid} ${_dataset}

    if [ "${_force}" -ne "1" ] ; then
            echo " "
            echo "  WARNING: this will destroy jail ${_fulluuid}"
            echo "  Dataset: ${_dataset}"
            echo " "
            echo -n "  Are you sure ? y[N]: "
            read _answer

        if [ "${_answer}" = "Y" -o "${_answer}" = "y" ] ; then
            if [ ! -z ${_state} ] ; then
                __die "cannot destroy ${_name} - jail is running!"
            fi

            __destroy_func ${_fulluuid} ${_dataset} ${_origin} ${_jail_type}
        else
            echo "  Command not confirmed.  No action taken."
        fi
    else
        if [ ! -z ${_state} ] ; then
            __stop_jail ${_fulluuid} ${_dataset}
        fi
        __destroy_func ${_fulluuid} ${_dataset} ${_origin} ${_jail_type}
    fi
}

__destroy_func () {
    local _fulluuid _dataset _origin _jail_type _base_inuse

    _fulluuid="$1"
    _dataset="$2"
    _origin="$3"
    _jail_type="$4"
    _base_inuse="$(zfs get -r -H -o value origin ${pool} | \
                 grep ${pool}/iocage/base > \
                 /dev/null 2>&1 ; echo $?)"

    echo "  Destroying: ${_fulluuid}"

    __unlink_tag ${_dataset}

    zfs destroy -fr ${_dataset}

    if [ "${_origin}" != "-" ] ; then
        echo "  Destroying clone origin: ${_origin}"
        zfs destroy -r ${_origin}
    fi

    if [ ${_jail_type} = "basejail" ] ; then
        if [ "${_base_inuse}" = "0" ] ; then
            zfs destroy -fr ${pool}/iocage/base@${_fulluuid} > /dev/null 2>&1
        fi
    fi
}

# check if our datasets exist, if not create them
# fixes https://github.com/iocage/iocage/issues/80
__check_filesystems () {
    local _altroot _filesystems _missing

    _missing=0
    _altroot="$(zpool get -H altroot ${pool} | awk '{print $3}')"
    # Prepend iocage/ so we can properly set a mount on the root 'iocage'
    # dataset.
    _filesystems="iocage
                  iocage/.defaults
                  iocage/download
                  iocage/jails
                  iocage/base"

    # Check for /etc/devfs.rules, this avoids an annoying error from grep later
    if [ ! -e "/etc/devfs.rules" ] ; then
        touch /etc/devfs.rules
    fi

    # Loop through and make sure the filesystems exist. Make sure you are root
    for _fs in $(echo ${_filesystems}) ; do
        zfs get -H creation ${pool}/${_fs} > /dev/null 2>&1
        if [ $? -ne 0 ] ; then
            _missing=1
            if [ "$(whoami)" != "root" ] ; then
                __die "Please run as root to create missing datasets."
            else
                __info "creating ${pool}/${_fs}"
                zfs create -p ${pool}/${_fs}
                zfs set mountpoint=/${_fs} ${pool}/${_fs}
                if [ ${_fs} == "iocage/.defaults" ] ; then
                    __configure_jail ${pool}/iocage/.defaults > /dev/null 2>&1
                    if [ $_altroot != "-" ] ; then
                        sed -i '' s#.*iocroot.*#iocroot="${_altroot}/iocage"# \
                            "${LIB}/ioc-globals"
                        export iocroot="${_altroot}/iocage"
                    elif [ $_altroot == "-" ] ; then
                        sed -i '' s#.*iocroot.*#iocroot="/iocage"# \
                            "${LIB}/ioc-globals"
                        export iocroot="/iocage"
                    fi
                fi
            fi
        fi
    done

    if [ ${_missing} -gt 0 ] ; then
        zfs mount -a
    fi

    export jail_datasets="$(zfs list -d3 -rH -o name ${pool}/iocage \
                          | grep -Ev "jails$|base$|download|${pool}/iocage$|*./root")"

    # Checks to see if the user changed the altroot and modify ioc-globals
    # If the user decided to unset their altroot, they need to run again as
    # root to set it back to the default location
    if [ ${_altroot} != "-" -a "$(whoami)" == "root" ] ; then
        sed -i '' s#.*iocroot.*#iocroot="${_altroot}/iocage"# \
            "${LIB}/ioc-globals"
        export iocroot="${_altroot}/iocage"
    elif [ ${_altroot} != "-" -a "$(whoami)" != "root" -a ${iocroot} != "${_altroot}/iocage" ] ; then
        __error "You changed the altroot of ${pool}"
        echo "  Please run as root to fix." >&2
        exit 1
    elif [ ${_altroot} == "-" -a "$(whoami)" == "root" ] ; then
        sed -i '' s#.*iocroot.*#iocroot="/iocage"# \
            "${LIB}/ioc-globals"
        export iocroot="/iocage"
    elif [ ${_altroot} == "-" -a "$(whoami)" != "root" -a ${iocroot} != "/iocage" ] ; then
        __error "You changed the altroot of ${pool}"
        echo "  Please run as root to fix." >&2
        exit 1
    fi
}

__check_children () {
    local _dataset _jail_datasets _fs _origin _tag _fulluuid \
          _uuid

    _fulluuid="$1"
    _dataset="$2"
    _jail_datasets="$(__find_jail ALL | \
                    grep -vE "${pool}/iocage/.defaults|${pool}/iocage/base/[0-9].?\>")"

    for _fs in $_jail_datasets ; do
        _origin="$(zfs get -H -o value origin $_fs | cut -f1 -d@)"
        _tag="$(zfs get -H -o value org.freebsd.iocage:tag $_fs)"
        _uuid="$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $_fs)"

        if [ $_origin == "$_dataset" ] ; then
            __die "jail has dependent clone, uuid: $_uuid ($_tag)"
        fi
    done
}

# Accepts one argument. Which is used as the UUID for the mount operations
__mount_basejail () {
    local _fulluuid="$1"

    # Mount the overlays needed for basejails
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/etc \
        ${iocroot}/jails/${_fulluuid}/root/etc
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/root \
        ${iocroot}/jails/${_fulluuid}/root/root
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/usr/home \
        ${iocroot}/jails/${_fulluuid}/root/usr/home
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/compat \
        ${iocroot}/jails/${_fulluuid}/root/compat
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/usr/local \
        ${iocroot}/jails/${_fulluuid}/root/usr/local
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/usr/obj \
        ${iocroot}/jails/${_fulluuid}/root/usr/obj
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/var \
        ${iocroot}/jails/${_fulluuid}/root/var

    # Check to make sure the ports directory exists
    if [ ! -e "${iocroot}/jails/${_fulluuid}/_/usr/ports" ] ; then
        mkdir "${iocroot}/jails/${_fulluuid}/_/usr/ports"
    fi

    # Mount the rest
    mount -t unionfs -o noatime,copymode=transparent \
        ${iocroot}/jails/${_fulluuid}/_/usr/ports \
        ${iocroot}/jails/${_fulluuid}/root/usr/ports

    # Mount tmpfs
    mount -t tmpfs tmpfs ${iocroot}/jails/${_fulluuid}/root/tmp
}

# Accepts one argument. Which is used as the UUID for the umount operations
__umount_basejail () {
    local _fulluuid="$1"

  # Unmounts all the basejails overlays and tmpfs so the jail can be manipulated
    umount ${iocroot}/jails/${_fulluuid}/root/compat    > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/etc       > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/root      > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/tmp       > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/var       > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/usr/home  > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/usr/local > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/usr/ports > /dev/null 2>&1
    umount ${iocroot}/jails/${_fulluuid}/root/usr/obj   > /dev/null 2>&1
}

# Accepts one argument. It uses that argument as the name/UUID.
__unset_inherited () {
    local _name _inherit

    _name="${1}"
    _inherit="$(zfs get -Hs "local" all ${pool}/iocage/jails/${_name} | \
              grep "org.freebsd.iocage" | \
              awk '{ print $2}')"
    for _p in ${_inherit} ; do
        echo -n "-o ${_p}=\"-\" "
    done
}
