#!/bin/sh

__import () {
    local _name _image _icount _icksum _new_cksum _old_cksum _uuid

    _name=$1
    _image="$(find $iocroot/images/ -name $_name\*.tar.xz)"
    _icount="$(echo $_image|wc -w)"
    _icksum="$(find $iocroot/images/ -name $_name\*.sha256)"

    if [ -z $_name ] ; then
        echo "  ERROR: Missing image UUID!"
        exit 1
    fi

    if [ $_icount -gt 1 ] ; then
        echo "  ERROR: Multiple matching images, please narrow down UUID."
        exit 1
    fi

    if [ $_icount -gt 0 ] ; then
        echo "* Found image $_image"
        echo "* Importing image $_image"

        if [ ! -f $_icksum ] ; then
            echo "  ERROR: Missing checksum file!"
            exit 1
        fi

        _new_cksum="$(sha256 -q $_image)"
        _old_cksum="$(cat $_icksum)"
        export type=thickjail
        _uuid="$(__create_jail "" -e)"

        if [ $_new_cksum != $_old_cksum ] ; then
            echo "  ERROR: Checksum mismatch. Exiting."
            exit 1
        else
            tar -xvJf $_image -C $iocroot/jails/${_uuid}/root
        fi

    else
        __die "image $_name not found!"
    fi

    cat $iocroot/jails/${_uuid}/root/etc/rc.conf | \
    sed -E "s/[a-zA-Z0-9]{8,}-.*-.*-.*-[a-zA-Z0-9]{12,}/$_uuid/g" \
    > $iocroot/jails/${_uuid}/rc.conf

    mv $iocroot/jails/${_uuid}/rc.conf \
    $iocroot/jails/${_uuid}/root/etc/rc.conf
}

__export () {
    # Export full jail
    # sha256
    local _name _dataset _fulluuid _jail_path _state _mountpoint _jail_type

    _name=$1
    _dataset=$(__find_jail $_name)
    _fulluuid="$(__check_name $_name)"
    _jail_path="$(__get_jail_prop mountpoint $_fulluuid)"
    _jail_type="$(__get_jail_prop type ${_fulluuid})"
    _state=$(jls|grep ${_jail_path} | wc -l)
    _mountpoint="$(__get_jail_prop mountpoint $_fulluuid)"

    if [ -z $_name ] ; then
        echo "  ERROR: Missing UUID!"
        exit 1
    fi

    if [ -z $_dataset ] ; then
        echo "  ERROR: $_name not found."
        exit 1
    fi

    if [ $_dataset == "multiple" ] ; then
        echo "  ERROR: Multiple matching UUIDs!"
        exit 1
    fi

    if [ "$_state" -gt "0" ] ; then
        echo "  ERROR: $_fulluuid is running!"
        echo "  Stop jail before exporting!"
        exit 1
    fi

    if [ ! -d "${iocroot}/images" ] ; then
        mkdir ${iocroot}/images
    fi

    # If the jail is a basejail, mount all the overlays
    if [ "${_jail_type}" == "basejail" ] ; then
        mount -t unionfs -o noatime,copymode=transparent \
            ${iocroot}/jails/${_fulluuid}/_/etc \
            ${iocroot}/jails/${_fulluuid}/root/etc
        mount -t unionfs -o noatime,copymode=transparent \
            ${iocroot}/jails/${_fulluuid}/_/root \
            ${iocroot}/jails/${_fulluuid}/root/root
        mount -t unionfs -o noatime,copymode=transparent \
            ${iocroot}/jails/${_fulluuid}/_/usr/home \
            ${iocroot}/jails/${_fulluuid}/root/usr/home
        mount -t unionfs -o noatime,copymode=transparent \
            ${iocroot}/jails/${_fulluuid}/_/usr/local \
            ${iocroot}/jails/${_fulluuid}/root/usr/local
        mount -t unionfs -o noatime,copymode=transparent \
            ${iocroot}/jails/${_fulluuid}/_/var \
            ${iocroot}/jails/${_fulluuid}/root/var
        mount -t tmpfs tmpfs ${iocroot}/jails/${_fulluuid}/root/tmp

        # Check to make sure the ports directory exists
        if [ ! -e "${iocroot}/jails/${_fulluuid}/_/usr/ports" ] ; then
            mkdir "${iocroot}/jails/${_fulluuid}/_/usr/ports"
        fi

        # Mount the rest
        mount -t unionfs -o noatime,copymode=transparent \
            ${iocroot}/jails/${_fulluuid}/_/usr/ports \
            ${iocroot}/jails/${_fulluuid}/root/usr/ports
    fi

    echo "* Exporting $_fulluuid"
    tar -cvJf $iocroot/images/$_fulluuid.tar.xz -C ${_mountpoint}/root . && \
    sha256 -q $iocroot/images/$_fulluuid.tar.xz > $iocroot/images/$_fulluuid.sha256
    echo "* Image saved to: $iocroot/images/$_fulluuid.tar.xz"
    echo "* Checksum created: $iocroot/images/$_fulluuid.sha256"

    # Unmount the overlays from before
    if [ "${_jail_type}" == "basejail" ] ; then
            __umount_basejail "${_fulluuid}"
    fi
}
