#!/bin/sh

# Configure properties -------------------------------------------------
__configure_jail () {
    local _value _default_value

    local CONF="$CONF_NET
                $CONF_JAIL
                $CONF_RCTL
                $CONF_CUSTOM
                $CONF_SYNC"

    echo "Configuring jail.."
    for prop in $CONF ; do
        prop_name=$prop
        eval prop="\$${prop}"
        if [ ! -z "$prop" ] ; then
            # find saved default value if any for the property
            _default_value="$(__get_default_prop $prop_name)"

            if [ "$_default_value" != "NONE" ] && [ "$_default_value" != "$prop" ] ; then
                _value="$_default_value"
            else
                _value="$prop"
            fi

            echo "** $prop_name=$_value"
            zfs set org.freebsd.iocage:$prop_name="$_value" $1
            unset _value
            if [ "$prop_name" == "tag" ] ; then
                __link_tag $1
            fi
        fi
    done

    for prop in $CONF_ZFS ; do
        prop_name=$prop
        eval prop="\$${prop}"
        _default_value="$(__get_default_prop $prop_name)"
        if [ ! -z "$prop" ] && [ "$prop" != "readonly" ] ; then
            # find saved default value if any for the property
            if [ "$_default_value" != "NONE" ] && [ "$_default_value" != "$prop" ] ; then
                _value="$_default_value"
            else
                _value="$prop"
            fi

            echo "** $prop_name=$_value"
            zfs set $prop_name="$_value" $1
        fi
    done
}

__jail_rc_conf () {
cat << EOT

cron_flags="$cron_flags -J 15"

# Disable Sendmail by default
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

# Run secure syslog
syslogd_flags="-c -ss"

# Enable IPv6
ipv6_activate_all_interfaces="YES"
EOT
}

# This is mostly for pkg autoinstall
__resolv_conf () {
    cat /etc/resolv.conf
}

__pkg_install () {
    local chrootdir="$1"

    if [ -e $pkglist ] ; then
        echo "* Installing extra packages.."
        for i in $(cat $pkglist) ; do
            pkg -c $chrootdir install -qy $i
        done
    fi
}

