#!/bin/sh

# Create the bhyve guest
__create_vmm () {
	size="$2"
	guestuuid=$uuid
	diskid="$(echo $guestuuid | cut -d "-" -f1)"
	tag=$(date "+%F@%T")
	if [ -z $size ]; then
		echo "You must enter a disk size. Ex: iocage vmmcreate 8G"
	else
		echo "Creating bhyve guest..."
		echo "Guest UUID:" $guestuuid
		echo "Disk ID:" $diskid
		echo "Disk size:" $size
		zfs create $pool/iocage/jails/$guestuuid
		zfs create -V $size -o volmode=dev $pool/iocage/disks/$diskid.img
		# Set defaults here until __configure_vmm is created. 
		# iocage set and get will work just fine after guest is created. 
		zfs set org.freebsd.iocage:host_hostuuid=$guestuuid $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:tag=$tag $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:tybe=vmm $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:cpu=1 $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:ram=256M $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:diskid=$diskid $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:size=$size $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:con=nmdm0 $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:tap=tap0 $pool/iocage/jails/$guestuuid
		zfs set org.freebsd.iocage:loader=bhyveload $pool/iocage/jails/$guestuuid
	fi
}
