#!/bin/sh

# Print supported releases----------------------------------
__print_release () {
    supported="10.2-RELEASE
                9.3-RELEASE"

    echo "Supported releases are: "
    for rel in $(echo $supported) ; do
        printf "%15s\n" "$rel"
    done
}

# Print defaults set in this script.
__print_defaults () {
    local _prop _prop_name _saved_default

    _CONF="$CONF_NET
           $CONF_JAIL
           $CONF_RCTL
           $CONF_CUSTOM
           $CONF_ZFS
           $CONF_SYNC
           $CONF_FTP
           $CONF_GIT"

    for _prop in $(echo $_CONF)  ; do
        _prop_name=$_prop
        eval _prop="\$${_prop}"

        if [ ! -z "${_prop}" ] ; then
            _saved_default="$(__get_jail_prop ${_prop_name} default)"
            if [ "${_saved_default}" != "none" ] ; then
                echo "${_prop_name}=${_saved_default}"
            else
                echo "${_prop_name}=${_prop}"
            fi
        fi
    done
}

# Get default value for property if one is found
__get_default_prop () {
    local _property _value

    _property="$1"
    _value="$(__get_jail_prop $_property default)"

    if [ "$_value" != '-' ] ; then
        echo "$_value"
    else
        echo "none"
    fi
}

# Find and return the jail's top level ZFS dataset

__find_jail () {
    local name=$1
    local jlist="/tmp/iocage-jail-list.$$"
    local jails="$(zfs list -d1 -rH -o name $pool/iocage/jails \
                 | grep -E \
                "^$pool/iocage/jails/[a-zA-Z0-9]{8,}-.*-.*-.*-[a-zA-Z0-9]{12,}$")"

    if [ "${name}" == "ALL" ] ; then
        for jail in $jails ; do
            echo $jail
        done
    elif [ "${name}" == "default" ] ; then
        echo "${pool}/iocage/.defaults"
    else
        for jail in $jails ; do
            found="$(echo $jail |grep -iE "^$pool/iocage/jails/$name"|wc -l)"
            local tag="$(zfs get -H -o value org.freebsd.iocage:tag $jail)"

            if [ "$found" -eq 1 ] ; then
                echo $jail >> $jlist
            fi

            if [ $tag == $name ] ; then
                echo $jail >> $jlist
            fi
        done

        if [ ! -e $jlist ] ; then
            exit 0
        fi

        if [ "$(cat $jlist|wc -l)" -eq "1" ] ; then
            cat $jlist
        elif [ "$(cat $jlist|wc -l)" -gt "1" ] ; then
            echo "multiple"
        fi
    fi

    rm  -f $jlist
}

__list_jails () {
    local jails=$(__find_jail ALL)
    local switch=$1
    local all_jids=$(jls -N -h jid | grep -v -x jid )
    local ioc_jids=""
    local non_ioc_jids=""

    if [ ! -z ${switch} ] && [ $switch == "-r" ] ; then
        echo "Downloaded releases:"
        local releases="$(zfs list -o name -Hr $pool/iocage/releases \
                        | grep RELEASE$ | cut -d \/ -f 4)"
        for rel in $(echo $releases) ; do
            printf "%15s\n" "$rel"
        done
        exit 0
    fi

    printf "%-4s  %-36s  %s  %s  %s\n" "JID" "UUID"  "BOOT"\
           "STATE" "TAG"
    for jail in $jails ; do
        uuid=$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)
        boot=$(zfs get -H -o value org.freebsd.iocage:boot $jail)
        tag=$(zfs get -H -o value org.freebsd.iocage:tag $jail)
        jail_path=$(zfs get -H -o value mountpoint $jail)
        state=$(jls | grep ${jail_path} | awk '{print$1}')
        template=$(zfs get -H -o value org.freebsd.iocage:template $jail)
        # get jid for iocage jails
        jid=$(jls -j "ioc-"$uuid  -h jid 2> /dev/null | grep -v -x "jid")
        if [ -z "$jid"  ] ; then
            jid="-"
        fi
        local ioc_jids=$ioc_jids" "$jid

        if [ -z "$state" ] ; then
            state=down
        else
            state=up
        fi

        if [ -z ${switch} ] ; then
            switch=zero
        fi

        if [ $switch == "-t" ] ; then
            if [ $template == "yes" ] ; then
                printf "%-4s  %-+.36s  %-3s   %-4s   %s\n" "$jid" "$uuid" \
                "$boot" "$state" "$tag"
            fi
        elif [ $switch != "-t" ] ; then
            if [ $template != "yes" ] ; then
                printf "%-4s  %-+.36s  %-4s  %-4s   %s\n" "$jid" "$uuid"  \
                "$boot" "$state" "$tag"
            fi
        fi
    done

    # create list of active jids not registered in iocage
    for all_jail in $all_jids ; do
        for ioc_jail in $ioc_jids ; do
            if [ "$all_jail" == "$ioc_jail" ] ; then
                local temp_loop_var=""
                break
            else
                local temp_loop_var=$all_jail

            fi
        done
    if [ -n "$temp_loop_var" ] ; then
        local non_ioc_jids=$non_ioc_jids" "$temp_loop_var
    fi
    done

    # output non iocage jails currently active
    if [ -n "$non_ioc_jids" ] ; then
        if [ $switch != "-t" ] ; then
            printf "%-+40s\n" "--- non iocage jails currently active ---"
            printf "%-4s  %-36s  %-15s  %s \n" "JID" "PATH"\
                  "IP4" "HOSTNAME"
            for jid in $non_ioc_jids ; do
                path=$(jls -j $jid  -h path | grep -v -x "path")
                ip4=$(jls -j $jid  -h ip4.addr | grep -v -x "ip4.addr")
                host_hostname=$(jls -j $jid  -h host.hostname | grep -v -x "host.hostname")
                printf "%-4s  %-36.36s  %-15s  %s\n" "$jid" "$path"  \
                        "$ip4" "$host_hostname"
            done
        fi
    fi
}

__print_disk () {
    local jails=$(__find_jail ALL)

    printf "%-36s  %-6s  %-5s  %-5s  %-5s  %-5s %-20s\n" "UUID" "CRT" "RES" "QTA" "USE" "AVA" "TAG"

    for jail in $jails ; do
        uuid=$(zfs get -H -o value org.freebsd.iocage:host_hostuuid $jail)
        crt=$(zfs get -H -o value compressratio $jail)
        res=$(zfs get -H -o value reservation $jail)
        qta=$(zfs get -H -o value quota $jail)
        use=$(zfs get -H -o value used $jail)
        ava=$(zfs get -H -o value available $jail)
        tag=$(zfs get -H -o value org.freebsd.iocage:tag $jail)

        printf "%-36s  %-6s  %-5s  %-5s  %-5s  %-5s %-20s\n" "$uuid" "$crt" "$res" "$qta" \
               "$use" "$ava" "$tag"
    done
}

__find_mypool () {
    local _comment _dupcheck

    pools="$(zpool list -H -o name)"
    _comment="$(zpool list -H -o name,comment | grep iocage)"
    _dupcheck="$(zpool list -H -o name,comment | grep iocage | wc -l)"
    found="0"

    if [ "$_dupcheck" -gt 1 ] ; then
        echo ""
        echo "  WARNING: You have more then one pool set for iocage use!"
        echo ""
        echo "**** POOLS ****"
        echo "$_comment"
        echo "***************"
        echo ""
        echo "  Please run 'iocage deactivate' on one of them"
        echo ""
        exit 1
    fi

    for i in $pools ; do
        mypool="$(zpool get comment $i | grep -v NAME | awk '{print $3}')"

        if [ "$mypool" == "iocage" ] ; then
            export pool=$i
            found=1
            break
        fi
    done

    if [ $found -ne 1 ] ; then
        if [ -n "$RC_PID" ]; then
            # RC_PID set means we are running from rc
            echo "ERROR: No pool for iocage jails found on boot ..exiting"
            exit 1
        else
            echo "Setting up zpool [$i] for iocage usage..."
            echo "If you wish to change zpool, use 'iocage activate'"
            zpool set comment=iocage $i
            export pool=$i
        fi
    fi
}

# Get jail properties
__get_jail_prop () {
    local _value _found _name _property _dataset _CONF

    _name="$2"
    _property="$1"
    _found="0"
    _dataset="$(__find_jail $_name)"
    _CONF="$CONF_NET
           $CONF_JAIL
           $CONF_RCTL
           $CONF_CUSTOM
           $CONF_SYNC
           $CONF_FTP
           $CONF_GIT"

    if [ -z "$_property" ] ; then
        echo "  ERROR: get failed, incorrect property syntax!"
        exit 1
    fi

    if [ -z "$_name" ] ; then
        echo "  ERROR: missing UUID or property!"
        exit 1
    fi

    if [ -z "$_dataset" ] ; then
        echo "  ERROR: jail $_name not found!"
        exit 1
    fi

    if [ "$_dataset" == "multiple" ] ; then
        echo "  ERROR: multiple matching UUIDs!"
        exit 1
    fi

    for prop in $_CONF ; do
        if [ $prop == $_property ] ; then
            _found=1
            _value="$(zfs get -H -o value org.freebsd.iocage:$prop \
                         $_dataset)"
            # Fix nonexistent property problem (zfs get returns "-")
            # info: https://github.com/iocage/iocage/issues/76
            if [ "$_value" == '-' ] ; then
                echo "none"
            else
                echo "$_value"
            fi

        elif [ $_property == "all" ] ; then
            _found=1
            _value="$(zfs get -H -o value org.freebsd.iocage:$prop \
                         $_dataset)"
            echo "$prop:$_value"
        fi
    done

    for prop in $CONF_ZFS ; do
        if [ $prop == $_property ] ; then
            _found=1
            _value="$(zfs get -H -o value $prop $_dataset)"
            echo "$_value"
        fi
    done

    if [ $_found -ne "1" ] ; then
        echo "  ERROR: unsupported property: $_property !"
        exit 1
    fi
}

__runtime () {
    local name=$1

    if [ -z $name ] ; then
        echo "  ERROR: missing UUID"
        exit 1
    fi

    local dataset=$(__find_jail $name)

    if [ -z $dataset ] ; then
        echo "  ERROR: $name not found"
        exit 1
    fi

    if [ $dataset == "multiple" ] ; then
        echo "  ERROR: multiple matching UUIDs!"
        exit 1
    fi

    local fulluuid="$(__check_name $name)"

    local state="$(jls -n -j ioc-${fulluuid} | wc -l)"

    if [ "$state" -eq "1" ] ; then
        local params="$(jls -nj ioc-${fulluuid})"
        for i in $params ; do
            echo "  $i"
        done
    else
        echo " ERROR: jail $fulluuid is not up.."
    fi
}

__get_jail_name () {
    for i in $@; do
        :;
    done

    echo $i
}

# search for executable prestart|poststart|prestop|poststop in jail_dir first,
# else use jail exec_<type> property unchanged
__findscript () {
    local name=$1
    # type should be one of prestart|poststart|prestop|poststop
    local type=$2
    local jail_path="$(__get_jail_prop mountpoint $name)"

    if [ -x "${jail_path}/${type}" ]; then
        echo "${jail_path}/${type}"
    else
        echo "$(__get_jail_prop exec_${type} $name)"
    fi
}

__check_name () {
    local name=$1

    if [ -z $name ] ; then
        echo "ERROR"
        exit 1
    fi

    local dataset=$(__find_jail $name)

    if [ -z $dataset ] ; then
        echo "  ERROR: jail $name not found!"
        exit 1
    fi

    if [ $dataset == "multiple" ] ; then
        echo "  ERROR: multiple matching UUIDs!"
        exit 1
    fi

    local uuid="$(__get_jail_prop host_hostuuid $name)"

    echo "$uuid"

}

__is_running () {
    local _fulluuid _state
    _fulluuid="$1"
    _running="$(jls -n| grep ioc-${_fulluuid} | wc -l)"

    echo "${_running}"
}
